### ISSUE TITLE
Skalierung von Lizenz-Logos in der Frontdoor

### ISSUE THREAD

**Issue by alw-bsz** [OPUS4/opus4-licences#18]
Das Logo zur Lizenz "Urheberrechtlich geschützt" / "In Copyright" (s. #2) liegt nicht in der passenden Größe für die Darstellung auf der Frontdoor vor. Damit es analog zu den Logos für die CC-Lizenzen als externer Link eingebunden oder später automatisiert heruntergeladen und in der richtigen Größe dargestellt werden kann, wird eine CSS-ID verwendet, die automatisch aus dem Namen der Lizenz (Feld `name`) abgeleitet wird. Für die ID wird ein Eintrag im CSS angelegt, über den das Logo skaliert wird.

**Comment by j3nsch** [comment]
Okay, aber das Ticket betrifft die Frontdoor und hätte damit in die Application gehört. Hier im OPUS4-Licence Paket geht es um Backend-Aspekte, nicht die visuelle Präsentation im User Interface. Keines der OPUS4-Pakete ist moment ein "Frontend"-Modul. Das User Interface wird allein durch die Application definiert.

**Comment by j3nsch** [comment]
Die Änderungen wurden in den Release übernommen.
